version: '2'
services:
  master:
    image: osrf/ros:indigo-desktop
    restart: never
    command: roscore
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      - "DISPLAY"
    mem_limit: 3g
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
